"""new

Revision ID: 2e83442e03ec
Revises: 
Create Date: 2019-05-08 14:32:59.507899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e83442e03ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'main', ['fin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'fin_id')
    # ### end Alembic commands ###
